### ISSUE TITLE
Manage Vertex AI pipelines

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#150]
# Overview

Introduce Argo Workflow Templates for managing pipelines of Vertex AI. Pipelines are not a Vertex AI entity and management, therefore, needs to happen in the operator.

- [x] Upload pipeline to Google Cloud
- [ ] Compile pipeline with KFPv2 SDK

# Notes

- Pipelines should be stored on GCS in directories for each pipeline, allowing deterministic GCS paths
- Workflow Templates should have the same integration points as for KFP. Integration tests should test against both
- The choice for KFP or Vertex AI should be made at the installation time of the operator using a flag in the Helm chart
- The compiler should accept a command line flag that defines the KFP SDK version to be used (v1 vs v2) which then decides what TFX DAG runner to use (https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/orchestration/experimental). The provider configuration will contain what version to use for the given provider
- Not part of this card: the decision on what DSL (TFX vs KFP) to use would be defined as part of the pipeline definition when we decide to support the KFP DSL

**Comment by alexgeorgousis** [comment]
Considerations on [Vertex AI Pipelines](https://cloud.google.com/vertex-ai/docs/pipelines/create-pipeline-template) feature:
- It's still in preview mode (unstable)
- It's not possible to upload a compiled TFX pipeline (Argo Workflow) to Vertex AI Pipelines (either using the KFP SDK or the [Artifact Registry REST API](https://cloud.google.com/vertex-ai/docs/pipelines/create-pipeline-template#create-a-repository))
  - The compiled pipeline needs to be a [KFP PipelineSpec](https://github.com/kubeflow/pipelines/blob/master/api/v2alpha1/pipeline_spec.proto#L50) protobuf object (in yaml)
  - A `PipelineSpec` can be generated by the [KFP Compiler](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/compiler.py#L29), given a pipeline created using the [KFP DSL](https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html)
  - We currently don't support KFP DSL pipelines
  - It might be possible to generate a KFP `PipelineSpec` representation of a TFX pipeline, but I haven't figured out an easy way to do this by looking at the KFP source code
