### ISSUE TITLE
Provider migration mechanism

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#194]
## Overview

The provider for operator resources can be changed only on resources which don't have a provider stored in their state.
The migration of previously created resources therefore currently necessitates a manual deletion of the resource prior to migration.

In order to simplify migration, a migration mechanism should be provided which takes this steps in the background without further user interaction.

## Notes:
- on KFP (and VAI) Pipelines can be deleted even if a RC exists. The Run will then fail at runtime

## Process for simple resources without dependencies or dependants:
- resource created with Provider `p1`
- provider change requested to `p2`
- the operator deletes the resource from `p1`
- the operator continues with the resource like a newly created resource

## Process for fixed dependencies (RC to Pipeline)
- Option 1: as the lifecycle is meant to be tracked by the user we expect the RunConfiguration to be updated (it will fail until this is done due to the Pipeline being deleted from `p1`)
- ~Option 2: always check existence of Pipeline. Fail RC (and potentially delete from provider) if Pipeline doesn't exist or if providers don't match (unmanaged versions of pipelines in KFP no longer supported)~

## Process for dependent resources:
- Pipeline and RC created with Provider `p1`, RC tracks Pipeline

### RC is changed first
- provider change of RC requested to `p2`
- the operator fails RC because the providers no longer match

### The Pipeline is changed first
- provider change of Pipeline requested to `p2`
- the operator deletes the Pipeline from `p1`
- the operator continues with the resource like a newly created resource
- if providers match: RC will now get updated. RC will fail otherwise

**Question**: should we track deletions (in general)

**Comment by paoloambrosio-skyuk** [comment]
Closing as not currently a priority.
