### ISSUE TITLE
Support Python 3.10, drop Python 3.7 support

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [sky-uk/kfp-operator#277]
Currently, the argo compiler only supports compiling TFX pipelines for Python version 3.7 and 3.10. However, Python 3.7 has been deprecated several months ago, while 3.10 are under TFX 1.14 support (with 3.11 planned). 

https://github.com/sky-uk/kfp-operator/blob/57c85fe9b08d8728af72e006b81c44afa669b270/argo/kfp-compiler/Dockerfile#L1-L25.

We will soon need to update TFX from 1.9.2 / 1.12.0 to 1.14 to take advantage of some key improvements:

* Trainer retry: this resolves an issue where Trainer component disconnects with the submitted training job in Vertex AI due to networking errors.
* New L4 and A100 80GB GPUs: we may see use cases that necessarily leverage these GPUs for training, given recent A100 global stockout issues.

Python 3.10 also provides quality of life changes for developers, which we would like to take advantage of to accelerate our development.

**Comment by jmendesky** [comment]
THis has been resolved in https://github.com/sky-uk/kfp-operator/pull/297
