### ISSUE TITLE
Support namespaced custom resources on providers

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#40]
### Overview

The KFP-Operator has been built without multi-user support. Custom resources, currently, are assumed to have globally unique names.
All providers should support duplicate names across namespaces.

#### Tasks

- all labeled resources should contain both the resource's name and namespace
- resource names should be namespaced

#### Open Questions

- can VAI Pipeline schedules have labels?

#### Notes

Migration will happen eventually as resources are synchronised. No manual migration procedures are needed.

#### Open Questions

KFP support requires research into mult-user isolation
https://www.kubeflow.org/docs/components/central-dash/profiles/

- install KFP with multi-user isolation, investigate and design a solution

**Comment by aidandunlop** [comment]
Rather than using profiles in KFP, I think namespaced pipelines is already a feature? https://github.com/kubeflow/pipelines/pull/4835
