### ISSUE TITLE
Provide information in pipeline update events that identify the pipeline's version

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#68]
### Overview

In order to manage advanced rollout scenarios, the model update events emitted when a new model is pushed should include information on what version of the pipeline has been trained so that listeners to these events can make decisions of it.
This information could be the name of the `RunConfiguration` or the pipeline version.

**Comment by stefania-popescu** [comment]
`RunConfiguration` name is present in the Run Completion Event. We can create a new issue if the pipeline version is required, including use case.
