### ISSUE TITLE
Allow configuration of Argo Workflow k8s options

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#8]
**Overview:**

For some pipelines, the default argo Kubernetes options may not be suitable. In these cases, we would like to support setting these parameters on the Pipelines Resource rather than in the pipeline's code.

**Examples:**
```
container_op.set_memory_request("2G")
```
```
container_op.add_pod_annotation("cluster-autoscaler.kubernetes.io/safe-to-evict", "false")
```
```
container_op.set_retry(num_retries=configs.settings.ARGO_RETRY)
```

**Comment by stefania-popescu** [comment]
Closing as outdated for now. Re-open if required.
